### ISSUE TITLE
Rails 3.2 pjax_rails jquery sizzle syntax error: unrecognized expression

### ISSUE THREAD

**Issue by ygamretuta** [rails/pjax_rails#44]
I am applying pjax on a link which has the href /search?p=true&q=d&t=c/ . The pjax functionality works, but it always spits the:

```
Error: Syntax error, unrecognized expression: /search?p=true&q=d&t=p
[Break On This Error]   

throw new Error( "Syntax error, unrecognized expression: " + msg );
```

which when inspected comes from Sizzle's:

``` javascript
Sizzle.error = function( msg ) {
throw new Error( "Syntax error, unrecognized expression: " + msg );
}; 
```

when Jquery fires:

``` javascript
xhr.send( ( s.hasContent && s.data ) || null );
```

**Comment by econder** [comment]
I'm having this issue currently and also found that removing the data-toggle from my bootstrap tabs, which are loading views into my pjax div, the issue goes away. Using rails 4.2.4 & rack-pjax 0.8.0.
