### ISSUE TITLE
Weird https issue

### ISSUE THREAD

**Issue by confact** [rails/pjax_rails#75]
Hi!
I installed this and it worked good on my dev, but ofc when i deployed it to production i stucked on https and http issue when clicking on a link:
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://***.com/category' cannot be created in a document with origin 'https://***.com'.
```
The links are just /category and such, so i don't know it is trying to go to http://. Do you guys know?

**Comment by confact** [comment]
Changed to turbolinks and it works. sad, because i want to use this with partial, and turbolinks 3.0's partial is still a bit buggy.

**Comment by route** [comment]
Can you create a reproducible app? That would be really helpful
